// Runs tools/solver.js headless in Node, loading modules through Vite so the /src imports resolve.
//   node tools/solve.mjs                     every level
//   node tools/solve.mjs 1-5 1-B --trace     chosen levels, with the route drawn on the map
//   node tools/solve.mjs --write-routes      also save the routes to src/routes.js (the hint ghosts)
//   node tools/solve.mjs 1-B --beam 6000 --maxT 40
//   node tools/solve.mjs 1-5 --K 12          coarser input (a decision every 0.1s): a rough difficulty check
//   node tools/solve.mjs 1-B --mods '{"boss":{"speed":12.1,"catchup":7.1,"delay":0.56}}'
//       boss scaled by 1/0.7: still solvable means a player at ~70% of the solver's pace escapes
import { writeFileSync } from 'node:fs';
import { createServer } from 'vite';

// The level builds its textures on canvases; headless, any 2D context call can be a no-op.
const noop = () => {};
const ctx2d = new Proxy({}, { get: (t, k) => (k in t ? t[k] : noop) });
globalThis.document = { createElement: () => ({ getContext: () => ctx2d }) };

const args = process.argv.slice(2);
const opt = (name, def) => (args.includes(`--${name}`) ? Number(args[args.indexOf(`--${name}`) + 1]) : def);
const server = await createServer({ appType: 'custom', server: { middlewareMode: true, hmr: false, ws: false }, logLevel: 'error' });
const { solve, trace } = await server.ssrLoadModule('/tools/solver.js');
const { LEVELS } = await server.ssrLoadModule('/src/levels.js');
const { ROUTES } = await server.ssrLoadModule('/src/routes.js');

const ids = args.filter((a) => LEVELS.some((l) => l.id === a));
const mods = args.includes('--mods') ? JSON.parse(args[args.indexOf('--mods') + 1]) : {};
const routes = { ...ROUTES };
for (const def of ids.length ? LEVELS.filter((l) => ids.includes(l.id)) : LEVELS) {
  const idx = LEVELS.indexOf(def);
  const t0 = performance.now();
  const r = solve(idx, { beam: opt('beam', def.boss ? 6000 : 2000), maxT: opt('maxT', 40), K: opt('K', 6), mods });
  const time = r && +r.time.toFixed(2);
  // Par rule from src/levels.js: ~1.3x the solver's time rounded up to 0.5s, +1s on Extended Thinking levels.
  const par = r && Math.ceil(time * 1.3 * 2) / 2 + (def.think ? 1 : 0);
  console.log(JSON.stringify({
    id: def.id, solved: !!r?.verified, time, par: def.par, suggestedPar: par, minBossGap: r?.minBossGap,
    searchMs: Math.round(performance.now() - t0),
  }));
  if (r && args.includes('--trace')) console.log(trace(idx, r, opt('K', 6)));
  if (r?.verified && opt('K', 6) === 6 && !args.includes('--mods')) routes[def.id] = r.actions.join('');
}
if (args.includes('--write-routes')) {
  const body = LEVELS.filter((l) => routes[l.id]).map((l) => `  '${l.id}': '${routes[l.id]}',`).join('\n');
  writeFileSync('src/routes.js', `// Generated by \`node tools/solve.mjs --write-routes\`: each level's solver route, one digit per
// action (see src/route.js). Regenerate after editing a level; the game disables hints on stale routes.
export const ROUTES = {
${body}
};
`);
}
await server.close();
