// Legend:
//   #  solid          X  deprecated block (crumbles)     P  start
//   =  real shimmer   ?  hallucinated shimmer (fake)     G  goal (Sonnet, or the button on boss levels)
//   s  small saw      S  big saw      H / V  big saw moving horizontally / vertically (in sync, unless the
//                                     level sets `sawLag` to stagger them into a left-to-right wave)
//   U  RLHF pad (launches you)        I  prompt-injection sign (mirrors controls)
//   R / r  429 gate, shut for the first / second half of each 3s beat     < / >  conveyor belt
//   C  checkpoint flag (deaths after touching it respawn there)
// Rows are top-to-bottom; short rows are padded with empty space.
// `par` is Dr. Overfit's "claimed" time; beat it for an A+. Set to ~1.3x the solver's time (tools/solver.js),
// rounded up to 0.5s, plus 1s on levels that need Extended Thinking.

// Long levels are built from screen-sized chunks laid side by side, bottom-aligned on the floor.
function chain(...chunks) {
  const h = Math.max(...chunks.map((c) => c.length));
  return Array.from({ length: h }, (_, r) =>
    chunks.map((c) => (c[r - h + c.length] ?? '').padEnd(Math.max(...c.map((row) => row.length)))).join(''),
  );
}

export const LEVELS = [
  {
    id: '1-1',
    name: 'Hello, World',
    par: 4.5,
    music: 'hello',
    hint: 'ARROWS / WASD move  ·  SPACE / Z jump (hold for height)  ·  hold SHIFT / X to run  ·  R restart',
    map: [
      '',
      '',
      '',
      '',
      '',
      '                                             G  ',
      '                                       #########',
      '                               #####   #########',
      '  P                   s        #####   #########',
      '##########   #######     ###########   #########',
      '##########sss#######sssss###########sss#########',
      '################################################',
    ],
  },
  {
    id: '1-2',
    name: 'Wall of Text',
    par: 4.5,
    music: 'wall',
    hint: 'Jump off walls to wall-jump. Hold towards a wall to slide down it slowly.',
    map: [
      '',
      '',
      '',
      '          ##',
      '          ##',
      '          ##                 G  ',
      '          ##   ######    #######',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '          ##   ##',
      '               ##',
      '               ##',
      '               ##',
      '   P           ##sssssssssssssss',
      '################################',
      '################################',
    ],
  },
  {
    id: '1-3',
    name: 'Gradient Descent',
    par: 5,
    music: 'descent',
    hint: 'Orange blocks are DEPRECATED: they crumble shortly after you touch them.',
    map: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '                          ##',
      '                     ##   ##    H       XXX',
      '  P                  ## V ##                     G',
      '######XXXXXXXX#####  ##   ##########        ########',
      '######        #####  ##   ##########        ########',
      '######        #####  ##   ##########        ########',
      '######        #####  ##   ##########        ########',
      '######ssssssss#####ss##sss##########ssssssss########',
      '####################################################',
    ],
  },
  {
    id: '1-4',
    name: 'Hallucination',
    par: 5.5,
    music: 'halluc',
    think: true,
    hint: 'Some platforms are HALLUCINATED. Hold C to use EXTENDED THINKING and see what is real. The clock keeps ticking.',
    map: [
      '',
      '',
      '',
      '',
      '                  ??',
      '             ==        ==',
      '        ??                  ???',
      '  P               ==                          G',
      '######  ==   ??        ??         ################',
      '######                      ===   ################',
      '######                            ################',
      '######                            ################',
      '######ssssssssssssssssssssssssssss################',
      '##################################################',
    ],
  },
  {
    id: '1-5',
    name: 'Human Feedback',
    par: 15.5,
    music: 'feedback',
    hint: 'Green thumbs-up pads are RLHF: land on one and it launches you. Steer in the air to stick the landing.',
    map: chain(
      [
        '              ####        ',
        '              ####        ',
        '              ####        ',
        '              ####        ',
        '              ####        ',
        '  P           ####        ',
        '########U#################',
        '##########################',
        '##########################',
      ],
      [
        '          ##############',
        '          ##############',
        '          ##############',
        '          ##############',
        '          ##############',
        '          ##############',
        '          ##############',
        '###UUU    ##############',
        '######ssss##############',
        '########################',
      ],
      [
        '                         UUU  ',
        '######                   ###  ',
        '######                   ###  ',
        '######           UUU     ###  ',
        '######           ###     ###  ',
        '######           ###     ###  ',
        '######   UUU     ###     ###  ',
        '######   ###     ###     ###  ',
        '######   ###     ###     ###  ',
        '######sss###sssss###sssss###ss',
        '##############################',
      ],
      [
        '',
        '',
        '',
        '',
        '',
        '',
        '######                  ',
        '######                  ',
        '######                  ',
        '######                  ',
        '######     S            ',
        '######                  ',
        '######                  ',
        '######                  ',
        '######                  ',
        '######                  ',
        '######            C     ',
        '######   ###############',
        '######sss###############',
        '########################',
      ],
      [
        '            S             ',
        '                          ',
        '                          ',
        '                       ###',
        '                       ###',
        '                       ###',
        '                       ###',
        '                       ###',
        '                       ###',
        '                       ###',
        '####U############U########',
        '##########################',
        '##########################',
      ],
      [
        '                    G   ',
        '              ##########',
        '              ##########',
        '          V   ##########',
        '              ##########',
        '              ##########',
        '              ##########',
        '              ##########',
        '              ##########',
        '######U#################',
        '########################',
        '########################',
      ],
    ),
  },
  {
    id: '1-6',
    name: 'Prompt Injection',
    par: 14.5,
    music: 'inject',
    sawLag: 0.12, // seconds per tile: the final V saws rise in a left-to-right wave you can hop along
    hint: 'IGNORE PREVIOUS INSTRUCTIONS signs mirror your controls for 2 seconds. Jump over them when you can.',
    map: chain(
      [
        '     ######                   ',
        '     ######                   ',
        '     ######                   ',
        '     ######                   ',
        '     ######                   ',
        '  P     I                     ',
        '####################  ########',
        '####################ss########',
        '##############################',
      ],
      [
        '             I      I         ',
        '                              ',
        '                              ',
        '   I                          ',
        '#####    ###    ###    ###    ',
        '#####ssss###ssss###ssss###ssss',
        '##############################',
      ],
      [
        '  #####                       ',
        '  #####                       ',
        '  #####                       ',
        '    I                         ',
        '######XXXXXXXXX    ###   #####',
        '######sssssssssssss###sss#####',
        '##############################',
      ],
      [
        '    ##                        ',
        '    ##                        ',
        '    ##      I                 ',
        '    ##   #####                ',
        '    ##   #####                ',
        '    ##   #####                ',
        '    ##   #####   ###          ',
        '    ##   #####                ',
        '    ##   #####                ',
        '    ##   #####         ###    ',
        '         #####                ',
        '  C      #####                ',
        '##############             ###',
        '##############sssssssssssss###',
        '##############################',
      ],
      [
        '          V    V    V         ',
        '     I                        ',
        '     I                        ',
        '     I                     G  ',
        '######   ##   ##   ##   ######',
        '######sss##sss##sss##sss######',
        '##############################',
      ],
    ),
  },
  {
    id: '1-7',
    name: 'Rate Limited',
    par: 17,
    music: 'ratelimit',
    think: true,
    hint: '429 gates slam shut on a beat, and crush anything inside. Learn the rhythm. EXTENDED THINKING slows them too.',
    map: chain(
      [
        '        ######################',
        '        ######################',
        '              R         r     ',
        '              R         r     ',
        '  P           R         r     ',
        '##############################',
        '##############################',
        '##############################',
      ],
      [
        '##rrrrrrRRRRRRrrrrrrRRRRRR  ##',
        '##ssssssssssssssssssssssssss##',
        '##############################',
      ],
      [
        '                ##############',
        '                ##############',
        '                 r       R    ',
        '                 r       R    ',
        '                 r       R C  ',
        '####XXXXXXXXXXXX##############',
        '####ssssssssssss##############',
        '##############################',
      ],
      [
        '            ???   ==          ',
        '      ===                     ',
        '                       rrr    ',
        '###         RRR            ###',
        '###ssssssssssssssssssssssss###',
        '##############################',
      ],
      [
        '    ######################    ',
        '    ######################    ',
        '     R                  r     ',
        '     R                  r     ',
        '     R    s    s    s   r  G  ',
        '##############################',
        '##############################',
        '##############################',
      ],
    ),
  },
  {
    id: '1-8',
    name: 'Data Pipeline',
    par: 13.5,
    music: 'pipeline',
    hint: 'Conveyors carry you along, and fling you further when you jump off them.',
    map: chain(
      [
        '  P                           ',
        '####>>>>>>>>>>            ####',
        '##############ssssssssssss####',
        '##############################',
      ],
      [
        '              <<<<<           ',
        '                              ',
        '     <<<<<               >>>>>',
        '###                         ##',
        '###sssssssssssssssssssssssss##',
        '##############################',
      ],
      [
        '                       #######',
        '                       #######',
        '                       #######',
        '                       #######',
        '                       #######',
        '                       #######',
        '                       #######',
        '                       #######',
        '##>>>>>>>>U            #######',
        '###########ssssssssssss#######',
        '##############################',
      ],
      [
        '  C I                         ',
        '######                        ',
        '######                        ',
        '######                        ',
        '######   <<<<<<<<             ',
        '######                        ',
        '######                        ',
        '######              >>>>>>>>  ',
        '######                        ',
        '######                      ##',
        '######ssssssssssssssssssssss##',
        '##############################',
      ],
      [
        '             S                ',
        '                              ',
        '                              ',
        '                              ',
        '               H              ',
        '                              ',
        '                              ',
        '                    >>>>>     ',
        '                              ',
        '       >>>>>                  ',
        '####U                       ##',
        '#####sssssssssssssssssssssss##',
        '##############################',
      ],
      [
        '  ##########################  ',
        '  ##########################  ',
        '        R           r         ',
        '        R           r         ',
        '        R           r      G  ',
        '##>>>>>>>>>>>>>>>>>>>>>>>#####',
        '##############################',
        '##############################',
      ],
    ),
  },
  {
    id: '1-B',
    name: 'The Gemini Twins',
    par: 26,
    music: 'twins',
    think: true,
    theme: 'cloud',
    // Solver: the optimal route stays ~10 tiles ahead; with the boss tuned to 70% of that pace it still escapes (~2.7 tiles).
    boss: { x: -5, y: 7, r: 1.5, speed: 8.5, near: 5, catchup: 5, delay: 0.8 },
    hint: 'RUN! Reach the BIG RED BUTTON.',
    map: chain(
      [
        '',
        '                                                                   H',
        '                                           ##   ###########',
        '                                           ##   ##          V  ##########',
        '                                           ##   ##',
        '                                           ##   ##',
        '                                           ##   ##',
        '                                           ##   ##',
        '                                           ##   ##',
        '                                           ##   ##',
        '                                                ##',
        '                                                ##',
        '                             ######XXXXXX#########',
        '   P                s        ######      #########                                     ',
        '############   ##########    ######      #########                          ##############',
        '############   ##########    ######      #########                          ##############',
        '############sss##########ssss######ssssss#########ssssssssssssssssssssssssss##############',
        '##########################################################################################',
      ],
      [
        '             ####             ',
        '             ####             ',
        '             ####             ',
        '             ####             ',
        '             ####             ',
        '             ####             ',
        '             ####             ',
        '######U##########     ########',
        '#################     ########',
        '#################sssss########',
        '##############################',
      ],
      [
        '>>>>>>>>>>>>>>>>          ####',
        '################          ####',
        '################ssssssssss####',
        '##############################',
      ],
      [
        '     H         H         H    ',
        '                              ',
        ' C       #         #          ',
        '##############################',
        '##############################',
        '##############################',
        '##############################',
      ],
      [
        '   ######                     ',
        '   ######                     ',
        '   ######                     ',
        '      I                       ',
        '##############  #######  #####',
        '##############  #######  #####',
        '##############ss#######ss#####',
        '##############################',
      ],
      [
        '          ???           ==    ',
        '                XXX   ??      ',
        '    ===                       ',
        '          ===                 ',
        '##                          ##',
        '##                          ##',
        '##ssssssssssssssssssssssssss##',
        '##############################',
      ],
      [
        '                        G     ',
        '                  ############',
        '                  ############',
        '         V        ############',
        '                  ############',
        '                  ############',
        '                  ############',
        '############U#################',
        '##############################',
        '##############################',
        '##############################',
      ],
    ),
  },
];
